title: Tabula Spreadsheet Extraction
description: Have a PDF with embedded tables? This Add-On runs the open source [Tabula library](https://tabula.technology) against a selected PDF and tries to identify and extract any tables. You can provide a Google Drive or Dropbox URL to a Tabula template you have generated already to run against the documents. If no template is provided, tabula will try to guess the boundaries of the tables within the document. 
type: object
documents:
  - selected
  - query
properties: 
  url: 
    title: URL of tabula template
    type: string
    format: uri
